/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Products */
    get: operations['list_products_products_get']
    put?: never
    /** Create Product */
    post: operations['create_product_products_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/{product_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Product */
    get: operations['get_product_products__product_id__get']
    put?: never
    post?: never
    /**
     * Deactivate Product
     * @description Take the product off the catalogue. The row survives for past orders.
     */
    delete: operations['deactivate_product_products__product_id__delete']
    options?: never
    head?: never
    /** Update Product */
    patch: operations['update_product_products__product_id__patch']
    trace?: never
  }
  '/carts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Cart */
    post: operations['create_cart_carts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts/{cart_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Cart */
    get: operations['get_cart_carts__cart_id__get']
    put?: never
    post?: never
    /** Delete Cart */
    delete: operations['delete_cart_carts__cart_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts/{cart_id}/items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add Item */
    post: operations['add_item_carts__cart_id__items_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts/{cart_id}/items/{product_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Item */
    delete: operations['remove_item_carts__cart_id__items__product_id__delete']
    options?: never
    head?: never
    /** Set Item Quantity */
    patch: operations['set_item_quantity_carts__cart_id__items__product_id__patch']
    trace?: never
  }
  '/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Orders */
    get: operations['list_orders_orders_get']
    put?: never
    /**
     * Create Order
     * @description Turn a cart into an order. The cart is consumed on success.
     */
    post: operations['create_order_orders_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/orders/{order_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Order */
    get: operations['get_order_orders__order_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Order Status */
    patch: operations['update_order_status_orders__order_id__patch']
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness probe, used by the Docker healthcheck and by CI.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** CartItemCreate */
    CartItemCreate: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string
      /** Quantity */
      quantity: number
    }
    /** CartItemRead */
    CartItemRead: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string
      /** Product Name */
      product_name: string
      /** Product Sku */
      product_sku: string
      /** Unit Price Cents */
      unit_price_cents: number
      /** Quantity */
      quantity: number
      /** Line Total Cents */
      line_total_cents: number
    }
    /** CartItemUpdate */
    CartItemUpdate: {
      /** Quantity */
      quantity: number
    }
    /** CartRead */
    CartRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** User Id */
      user_id: string | null
      /** Items */
      items: components['schemas']['CartItemRead'][]
      /** Total Cents */
      total_cents: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** OrderCreate */
    OrderCreate: {
      /**
       * Cart Id
       * Format: uuid
       */
      cart_id: string
      /**
       * Customer Email
       * Format: email
       */
      customer_email: string
      /** Customer Name */
      customer_name: string
      /** Shipping Address */
      shipping_address: string
      /** Shipping Postal Code */
      shipping_postal_code: string
      /** Shipping City */
      shipping_city: string
      /** Shipping Country */
      shipping_country: string
    }
    /** OrderItemRead */
    OrderItemRead: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string
      /** Product Name */
      product_name: string
      /** Product Sku */
      product_sku: string
      /** Unit Price Cents */
      unit_price_cents: number
      /** Quantity */
      quantity: number
      /** Line Total Cents */
      line_total_cents: number
    }
    /** OrderRead */
    OrderRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** User Id */
      user_id: string | null
      status: components['schemas']['OrderStatus']
      /** Total Cents */
      total_cents: number
      /** Customer Email */
      customer_email: string
      /** Customer Name */
      customer_name: string
      /** Shipping Address */
      shipping_address: string
      /** Shipping Postal Code */
      shipping_postal_code: string
      /** Shipping City */
      shipping_city: string
      /** Shipping Country */
      shipping_country: string
      /** Items */
      items: components['schemas']['OrderItemRead'][]
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * OrderStatus
     * @enum {string}
     */
    OrderStatus: 'pending' | 'paid' | 'shipped' | 'cancelled'
    /** OrderUpdate */
    OrderUpdate: {
      status: components['schemas']['OrderStatus']
    }
    /** Page[OrderRead] */
    Page_OrderRead_: {
      /** Items */
      items: components['schemas']['OrderRead'][]
      /** Total */
      total: number
    }
    /** Page[ProductRead] */
    Page_ProductRead_: {
      /** Items */
      items: components['schemas']['ProductRead'][]
      /** Total */
      total: number
    }
    /** ProductCreate */
    ProductCreate: {
      /** Sku */
      sku: string
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /** Image Url */
      image_url?: string | null
      /** Price Cents */
      price_cents: number
      /**
       * Stock
       * @default 0
       */
      stock: number
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
    }
    /** ProductRead */
    ProductRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Sku */
      sku: string
      /** Name */
      name: string
      /** Description */
      description: string | null
      /** Image Url */
      image_url: string | null
      /** Price Cents */
      price_cents: number
      /** Stock */
      stock: number
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** ProductUpdate */
    ProductUpdate: {
      /** Sku */
      sku?: string | null
      /** Name */
      name?: string | null
      /** Description */
      description?: string | null
      /** Image Url */
      image_url?: string | null
      /** Price Cents */
      price_cents?: number | null
      /** Stock */
      stock?: number | null
      /** Is Active */
      is_active?: boolean | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_products_products_get: {
    parameters: {
      query?: {
        include_inactive?: boolean
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ProductRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_product_products_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_product_products__product_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        product_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deactivate_product_products__product_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        product_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_product_products__product_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        product_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_cart_carts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartRead']
        }
      }
    }
  }
  get_cart_carts__cart_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        cart_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_cart_carts__cart_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        cart_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_item_carts__cart_id__items_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        cart_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CartItemCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_item_carts__cart_id__items__product_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        cart_id: string
        product_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_item_quantity_carts__cart_id__items__product_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        cart_id: string
        product_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CartItemUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_orders_orders_get: {
    parameters: {
      query?: {
        status?: components['schemas']['OrderStatus'] | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_OrderRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_order_orders_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_order_orders__order_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        order_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_order_status_orders__order_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        order_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
