"""ajoute la categorie des produits

Revision ID: c241427491c7
Revises: cb164572d04d
Create Date: 2026-09-11 11:33:51.055783

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c241427491c7"
down_revision: str | None = "cb164572d04d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("category", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_column("products", "category")
    # ### end Alembic commands ###
