"""ajoute l image des produits

Revision ID: cb164572d04d
Revises: f25275a413ca
Create Date: 2026-09-10 14:04:48.318929

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "cb164572d04d"
down_revision: str | None = "f25275a413ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("image_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_url")
    # ### end Alembic commands ###
